name: dz-caucasus
channels:
  - davasey
  - conda-forge
dependencies:
  - python=3.10
  - pandas=1.5.1
  - geoscripts
  - openpyxl
  - xlrd
  - ipykernel
  - jupyter
  - r-irkernel
  - r-isoplotr=5.2
